/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-26 09:50:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/board/../include/header.jsp", Long.valueOf(1685094385524L));
    _jspx_dependants.put("/WEB-INF/views/board/../include/footer.jsp", Long.valueOf(1685094385550L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/board.css\" rel=\"stylesheet\">\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header-style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\" alt=\"logo\">\r\n");
      out.write("            <div class=\"title\" class=\"clearfix\">Camping</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"menu clearfix\">\r\n");
      out.write("                <div class=\"menu-down\">\r\n");
      out.write("                    <a href=\"#\"  id=\"reservation\">예약하기</a>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a  href=\"#\">지역검색</a>\r\n");
      out.write("                        <a  href=\"#\">테마검색</a>\r\n");
      out.write("                        <a  href=\"#\">날짜검색</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu-down\">\r\n");
      out.write("                    <a href=\"#\" class=\"in-menu\" id=\"board\">게시판</a>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a  href=\"#\">캠핑후기</a>\r\n");
      out.write("                        <a  href=\"#\">꿀팁공유</a>\r\n");
      out.write("                        <a  href=\"#\">메이트찾기</a>\r\n");
      out.write("                        <a  href=\"#\">건의사항</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"menu-down\">\r\n");
      out.write("                    <a href=\"#\" class=\"in-menu\" id=\"view\">캠핑장 둘러보기</a>\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                        <a  href=\"#\">둘러보기</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- <div class=\"in-menu\" id=\"reservation\">예약하기</div>\r\n");
      out.write("                <div class=\"in-menu\" id=\"view\">캠핑장 둘러보기</div>\r\n");
      out.write("                <div class=\"in-menu\" id=\"board\">게시판</div> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-right\">\r\n");
      out.write("                <input type=\"text\" class=\"search clearfix\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("                <div class=\"profile\">\r\n");
      out.write("                    <img class=\"profile-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/profile.png\" alt=\"profile\">\r\n");
      out.write("                    <a href=\"#\" class=\"user\">홍길동님</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section-dropdown\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div></div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<article class=\"board\">\r\n");
      out.write("    <div class=\"board-selector\">\r\n");
      out.write("        <a href=\"\">후기</a>\r\n");
      out.write("        <a href=\"\">꿀팁</a>\r\n");
      out.write("        <a href=\"\">메이트찾기</a>\r\n");
      out.write("        <a href=\"\">건의사항</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <table>\r\n");
      out.write("        \r\n");
      out.write("        <th class=\"head\"></th>\r\n");
      out.write("        <th class=\"title\">제목</th>\r\n");
      out.write("        <th class=\"writer\">작성자</th>\r\n");
      out.write("        <th class=\"regDate\">작성일</th>\r\n");
      out.write("        <th class=\"hit\">조회</th>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>후기</td>\r\n");
      out.write("            <td>너무 좋아요</td>\r\n");
      out.write("            <td>캠핑초보</td>\r\n");
      out.write("            <td>23-05-24</td>\r\n");
      out.write("            <td>23</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>매칭</td>\r\n");
      out.write("            <td>같이 노실분?</td>\r\n");
      out.write("            <td>심심한사람</td>\r\n");
      out.write("            <td>23-05-23</td>\r\n");
      out.write("            <td>12</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("            <td></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("    </table>\r\n");
      out.write("    <div class=\"page\">\r\n");
      out.write("        <div>이전</div>\r\n");
      out.write("        <div>1</div>\r\n");
      out.write("        <div>2</div>\r\n");
      out.write("        <div>3</div>\r\n");
      out.write("        <div>4</div>\r\n");
      out.write("        <div>5</div>\r\n");
      out.write("        <div>다음</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header-style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\" alt=\"logo\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"footer-info\">\r\n");
      out.write("                    개인 정보 처리 방침 | 고객센터 | 이용약관 | 전체서비스 <br>\r\n");
      out.write("                    주소: 서울 마포구 백범로23, 신수동 63-14 <br>\r\n");
      out.write("                    tel: 02-248-3657 <br>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-text\">\r\n");
      out.write("                    고객센터: 02-232-5598 |\r\n");
      out.write("                    평일: 09:00 ~ 18:00(점심시간 12:30 ~ 13:30) <br>\r\n");
      out.write("                    대표자: 박이김권 |\r\n");
      out.write("                    0311wlsgus@gmail.com\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
